export const StoragesProperties = [
  'RIDINEIN@UTOKEN',
  'RIDINEIN@UOUTLETSTR',
  'RIDINEIN@CRCTG',
  'RIDINEIN@CRSUBCTG',
  'RIDINEIN@SMGTR',
  'RIDINEIN@CRTSLCT',
  'RIDINEIN@SLTPYMNT',
  'RIDINEIN@USERINFO',
  'RIDINEIN@SLTPYMNT',
  'RIDINEIN@INVINFO',
  'RIDINEIN@CURRSEARCH'
] as const
